<?xml version="1.0" encoding="utf-8"?><Database Name="ComicTruyen" Class="DataMangaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-2S0CP2JK\SQLEXPRESS01;Initial Catalog=ComicTruyen;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MangaStoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BanChay" Member="BanChays">
    <Type Name="BanChay">
      <Column Name="MaBanChay" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BanChay" Member="BanChay1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="BanChay_IDBanChay" Member="IDBanChays" ThisKey="MaBanChay" OtherKey="MaBanChay" Type="IDBanChay" />
    </Type>
  </Table>
  <Table Name="dbo.VIETSACH" Member="VIETSACHes">
    <Type Name="VIETSACH">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VaiTro" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Vitri" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="VIETSACH_TACGIA" Member="TACGIA" ThisKey="MaTG" OtherKey="MaTG" Type="TACGIA" Cardinality="One" />
      <Association Name="TRUYEN_VIETSACH" Member="TRUYEN" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="TRUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDONHANG" Member="CHITIETDONHANGs">
    <Type Name="CHITIETDONHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Dongia" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="CHITIETDONHANG_DONDATHANG" Member="DONDATHANG" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DONDATHANG" Cardinality="One" />
      <Association Name="TRUYEN_CHITIETDONHANG" Member="TRUYEN" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="TRUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dathanhtoan" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Tinhtranggiaohang" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Ngaydat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ngaygiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHITIETDONHANG_DONDATHANG" Member="CHITIETDONHANG" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="CHITIETDONHANG" IsForeignKey="true" />
      <Association Name="User_DONDATHANG" Member="User" ThisKey="MaUser" OtherKey="MaUser" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIá" Member="GIás">
    <Type Name="GIá">
      <Column Name="MaGia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="GIá_GiaTruyen" Member="GiaTruyens" ThisKey="MaGia" OtherKey="MaGia" Type="GiaTruyen" />
    </Type>
  </Table>
  <Table Name="dbo.GiaTruyen" Member="GiaTruyens">
    <Type Name="GiaTruyen">
      <Column Name="IdGia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GIá_GiaTruyen" Member="GIá" ThisKey="MaGia" OtherKey="MaGia" Type="GIá" IsForeignKey="true" />
      <Association Name="TRUYEN_GiaTruyen" Member="TRUYEN" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="TRUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IDBanChay" Member="IDBanChays">
    <Type Name="IDBanChay">
      <Column Name="idBanChay" Member="idBanChay1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaBanChay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BanChay_IDBanChay" Member="BanChay" ThisKey="MaBanChay" OtherKey="MaBanChay" Type="BanChay" IsForeignKey="true" />
      <Association Name="TRUYEN_IDBanChay" Member="TRUYEN" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="TRUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MACOMIC" Member="MACOMICs">
    <Type Name="MACOMIC">
      <Column Name="MC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="THELOAI_MACOMIC" Member="THELOAI" ThisKey="MaTL" OtherKey="MaTL" Type="THELOAI" IsForeignKey="true" />
      <Association Name="TRUYEN_MACOMIC" Member="TRUYEN" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="TRUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MAQUANHE" Member="MAQUANHEs">
    <Type Name="MAQUANHE">
      <Column Name="MaQH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHAXUATBAN_MAQUANHE" Member="NHAXUATBAN" ThisKey="MaNXB" OtherKey="MaNXB" Type="NHAXUATBAN" IsForeignKey="true" />
      <Association Name="TRUYEN_MAQUANHE" Member="TRUYEN" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="TRUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHAXUATBAN" Member="NHAXUATBANs">
    <Type Name="NHAXUATBAN">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHAXUATBAN_MAQUANHE" Member="MAQUANHEs" ThisKey="MaNXB" OtherKey="MaNXB" Type="MAQUANHE" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Tieusu" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="VIETSACH_TACGIA" Member="VIETSACH" ThisKey="MaTG" OtherKey="MaTG" Type="VIETSACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THELOAI" Member="THELOAIs">
    <Type Name="THELOAI">
      <Column Name="MaTL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="THELOAI_MACOMIC" Member="MACOMICs" ThisKey="MaTL" OtherKey="MaTL" Type="MACOMIC" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="MaUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Matkhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_DONDATHANG" Member="DONDATHANGs" ThisKey="MaUser" OtherKey="MaUser" Type="DONDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.TRUYEN" Member="TRUYENs">
    <Type Name="TRUYEN">
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Giaban" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TRUYEN_VIETSACH" Member="VIETSACHes" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="VIETSACH" />
      <Association Name="TRUYEN_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="CHITIETDONHANG" />
      <Association Name="TRUYEN_GiaTruyen" Member="GiaTruyens" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="GiaTruyen" />
      <Association Name="TRUYEN_IDBanChay" Member="IDBanChays" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="IDBanChay" />
      <Association Name="TRUYEN_MACOMIC" Member="MACOMICs" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="MACOMIC" />
      <Association Name="TRUYEN_MAQUANHE" Member="MAQUANHEs" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="MAQUANHE" />
      <Association Name="TRUYEN_IDNoiBat" Member="IDNoiBats" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="IDNoiBat" />
    </Type>
  </Table>
  <Table Name="dbo.IDNoiBat" Member="IDNoiBats">
    <Type Name="IDNoiBat">
      <Column Name="idNoiBat" Member="idNoiBat1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNoiBat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TRUYEN_IDNoiBat" Member="TRUYEN" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="TRUYEN" IsForeignKey="true" />
      <Association Name="NoiBat_IDNoiBat" Member="NoiBat" ThisKey="MaNoiBat" OtherKey="MaNoiBat" Type="NoiBat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NoiBat" Member="NoiBats">
    <Type Name="NoiBat">
      <Column Name="MaNoiBat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiBat" Member="NoiBat1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NoiBat_IDNoiBat" Member="IDNoiBats" ThisKey="MaNoiBat" OtherKey="MaNoiBat" Type="IDNoiBat" />
    </Type>
  </Table>
</Database>